[project]
name = 'Legal-Service-Marketplace'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attorney-verificatio]
path = 'contracts/attorney-verificatio.clar'
clarity_version = 2
epoch = 2.5

[contracts.client-verification]
path = 'contracts/client-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
